### ISSUE TITLE
Page scrolling - using the tabs in the header- in the 2nd language site is not working

### ISSUE THREAD

**Issue by Oxko** [themefisher/meghna-hugo#156]
Hi, Could you help please, how to imply the tab config for the site in an other language? (that "about" tab scrolls to the "about" section) . The configuration works fine for the english version, but for the french it does not work, goes to the english sections when clicking on the tabs. 

Thanks a lot in advance.

**Comment by somratpro** [comment]
Hello @Oxko 

This is a known issue, we are trying to figure out why this is happening, and how can we fix it. Thank you

**Comment by Oxko** [comment]
Hi @somratpro
I found the solution, just for others it might help I post it here. 

In the config.toml for each translated section in the menu 
for the "pre" have to add the prefix of the language, so for french for example it goes with 
pre = "fr/#"

and do this for each translated tab. Now it works perfectly.

**Comment by Oxko** [comment]
unfortunately when I push it to master it doesnt work anymore this way, only on local server. 
if you find the solution could you help?

**Comment by somratpro** [comment]
This issue has been fixed.

**Comment by Oxko** [comment]
Hi @somratpro . It is not fixed on my side. nor with the pre adding second language nor the original way. 
What to do on my side to fix it too?

**Comment by somratpro** [comment]
download the theme separately, and run hugo on it.

**Comment by Oxko** [comment]
hi @somratpro . I could not download the template as i wouldnt wanna loose all the changes and updates i made in the last few weeks. 
I copied in only the part i found you changed in navigation html. 

However I see I have 2 language prefixes in the absolute url. 
hu/hu/#about
Therefore I guess the scrolling in second language doesnt work, if you say the site is fixed on your side. 

I have looked around where it is duplicated but didnt find any issues. could you help how to fix this?

**Comment by Oxko** [comment]
HI @somratpro! it works now! one url is not responding only. How to add the url to the banner in the second language? Could you advise? The same way as in the english one it does not work. Thanks.

**Comment by somratpro** [comment]
actually i am trying to say that, first you need to check if it's working or not by download the theme separately. if it's work, then implement it on your existing site. if it's not work, then let me know
